package com.vv.personal.twm.portfolio.model.tracking;

/**
 * @author Vivek
 * @since 2025-11-30
 */
public enum ProgressTracker {
  READY,
  READY_BANK,
  READY_MARKET,
  LOADING,

  LOADING_BANK,
  LOADING_BANK_POPULATE_ACCOUNTS,
  LOADING_BANK_POPULATE_DEPOSITS,
  LOADING_BANK_DEPOSITS_MAP,

  LOADING_MARKET,
  LOADING_MARKET_POPULATE_PORTFOLIO,
  LOADING_MARKET_POPULATE_DIVIDENDS,
  LOADING_MARKET_POPULATE_DIVIDENDS_YIELD,
  LOADING_MARKET_COMPUTE_ACB,
  LOADING_MARKET_COMPUTE_PNL,
  LOADING_MARKET_COMPUTE_CUMULATIVE_DIVIDENDS,
  LOADING_MARKET_COMPUTE_SECTOR_AGGR,
  LOADING_MARKET_LOAD_ANALYSIS,

  POSITION_ZERO
}
